package net.runelite.client.plugins.ElTickCooker;

public enum ElTickCookerState
{
	ANIMATING,
	FIND_OBJECT,
	MISSING_ITEMS,
	MOVING,
	TIMEOUT,
	BANK_NOT_FOUND,
	FIND_BANK,
	DEPOSIT_ITEMS,
	HANDLE_BREAK,
	UNHANDLED_STATE,
	WITHDRAW_ITEMS,
	COOK_WIDGET;
}
